# Generated by Django 4.0.6 on 2022-07-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.CharField(max_length=50, verbose_name='아이디어명: ')),
                ('photo', models.ImageField(blank=True, upload_to='posts/%Y%m%d', verbose_name='Image: ')),
                ('content', models.TextField(verbose_name='아이디어 설명: ')),
                ('interest', models.IntegerField(verbose_name='아이디어 관심도: ')),
                ('tool', models.CharField(max_length=50, verbose_name='예상 개발툴: ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름:')),
                ('kind', models.CharField(max_length=50, verbose_name='종류: ')),
                ('t_content', models.TextField(verbose_name='개발툴 설명: ')),
            ],
        ),
    ]
