# Generated by Django 4.0.6 on 2022-07-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='아이디어 설명'),
        ),
        migrations.AlterField(
            model_name='post',
            name='idea',
            field=models.CharField(max_length=50, verbose_name='아이디어명'),
        ),
        migrations.AlterField(
            model_name='post',
            name='interest',
            field=models.IntegerField(verbose_name='아이디어 관심도'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='posts/%Y%m%d', verbose_name='사진'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tool',
            field=models.CharField(max_length=50, verbose_name='예상 개발툴'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='kind',
            field=models.CharField(max_length=50, verbose_name='종류'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=50, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='t_content',
            field=models.TextField(verbose_name='개발툴 설명'),
        ),
    ]
